gapic_generator_version: 2.42.0
googleapis_commitish: a91d1a37cb86a0e49fdc21d8b4416eb1c2a083ec
libraries_bom_version: 26.43.0
libraries:
  - api_shortname: pubsub
    name_pretty: Cloud Pub/Sub
    api_reference: https://cloud.google.com/pubsub/
    product_documentation: https://cloud.google.com/pubsub/docs/
    client_documentation: https://cloud.google.com/java/docs/reference/google-cloud-pubsub/latest/history
    api_description: is designed to provide reliable, many-to-many, asynchronous messaging between applications. Publisher applications can send messages to a topic and other applications can subscribe to that topic to receive the messages. By decoupling senders and receivers, Google Cloud Pub/Sub allows developers to communicate between independently written applications.
    issue_tracker: https://issuetracker.google.com/savedsearches/559741
    release_level: stable
    language: java
    repo: googleapis/java-pubsub
    repo_short: java-pubsub
    distribution_name: com.google.cloud:google-cloud-pubsub
    codeowner_team: '@googleapis/api-pubsub'
    api_id: pubsub.googleapis.com
    library_type: GAPIC_COMBO
    requires_billing: true
    recommended_package: com.google.cloud.pubsub.v1
    GAPICs:
      - proto_path: google/pubsub/v1
